import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Layout } from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Users, Gift, Share2, TrendingUp, CheckCircle, Copy, ExternalLink } from "lucide-react";

export default function AffiliateRegister() {
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [referralCode, setReferralCode] = useState("");
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    email: "",
    socialLink: "",
    bankName: "",
    bankAccount: "",
    accountName: "",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name || !formData.phone || !formData.socialLink) {
      toast.error("Vui lòng điền đầy đủ thông tin bắt buộc");
      return;
    }

    setIsSubmitting(true);

    try {
      const { data, error } = await supabase
        .from('affiliates')
        .insert({
          name: formData.name,
          phone: formData.phone,
          email: formData.email || null,
          social_link: formData.socialLink,
          bank_name: formData.bankName || null,
          bank_account: formData.bankAccount || null,
          account_name: formData.accountName || null,
          referral_code: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) {
        if (error.code === '23505') {
          toast.error("Số điện thoại đã được đăng ký làm CTV");
        } else {
          throw error;
        }
        return;
      }

      setReferralCode(data.referral_code);
      setShowSuccess(true);
      toast.success("Đăng ký thành công! Chờ admin duyệt nhé.");

    } catch (error) {
      console.error('Error registering affiliate:', error);
      toast.error("Có lỗi xảy ra, vui lòng thử lại");
    } finally {
      setIsSubmitting(false);
    }
  };

  const copyReferralLink = () => {
    const link = `${window.location.origin}?ref=${referralCode}`;
    navigator.clipboard.writeText(link);
    toast.success("Đã copy link giới thiệu!");
  };

  if (showSuccess) {
    return (
      <Layout>
        <div className="container mx-auto px-4 py-8 max-w-lg">
          <Card className="border-green-200 bg-green-50">
            <CardContent className="pt-6 text-center space-y-4">
              <CheckCircle className="h-16 w-16 text-green-500 mx-auto" />
              <h2 className="text-2xl font-bold text-green-700">Đăng ký thành công!</h2>
              <p className="text-muted-foreground">
                Admin sẽ duyệt đơn đăng ký của bạn trong 1-2 ngày làm việc.
                Sau khi được duyệt, bạn có thể bắt đầu chia sẻ và nhận hoa hồng!
              </p>
              
              <div className="bg-white p-4 rounded-lg border space-y-2">
                <p className="text-sm text-muted-foreground">Mã giới thiệu của bạn:</p>
                <div className="flex items-center gap-2 justify-center">
                  <span className="text-2xl font-bold text-primary">{referralCode}</span>
                  <Button variant="outline" size="icon" onClick={copyReferralLink}>
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </div>

              <Button onClick={() => navigate("/")} className="w-full">
                Về trang chủ
              </Button>
            </CardContent>
          </Card>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Hero section */}
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold mb-4">Trở thành Cộng Tác Viên Purin Shop</h1>
            <p className="text-muted-foreground text-lg">
              Chia sẻ sản phẩm yêu thích và nhận hoa hồng cho mỗi đơn hàng thành công
            </p>
          </div>

          {/* Benefits */}
          <div className="grid md:grid-cols-4 gap-4 mb-8">
            <Card className="text-center">
              <CardContent className="pt-6">
                <Share2 className="h-10 w-10 mx-auto mb-2 text-primary" />
                <h3 className="font-semibold">Chia sẻ dễ dàng</h3>
                <p className="text-sm text-muted-foreground">Link riêng cho mỗi CTV</p>
              </CardContent>
            </Card>
            <Card className="text-center">
              <CardContent className="pt-6">
                <Gift className="h-10 w-10 mx-auto mb-2 text-primary" />
                <h3 className="font-semibold">Hoa hồng 5-10%</h3>
                <p className="text-sm text-muted-foreground">Trên mỗi đơn thành công</p>
              </CardContent>
            </Card>
            <Card className="text-center">
              <CardContent className="pt-6">
                <TrendingUp className="h-10 w-10 mx-auto mb-2 text-primary" />
                <h3 className="font-semibold">Thanh toán hàng tuần</h3>
                <p className="text-sm text-muted-foreground">Chuyển khoản trực tiếp</p>
              </CardContent>
            </Card>
            <Card className="text-center">
              <CardContent className="pt-6">
                <Users className="h-10 w-10 mx-auto mb-2 text-primary" />
                <h3 className="font-semibold">Hỗ trợ 24/7</h3>
                <p className="text-sm text-muted-foreground">Được hỗ trợ nhiệt tình</p>
              </CardContent>
            </Card>
          </div>

          {/* Commission info */}
          <Card className="mb-8 border-primary/20 bg-primary/5">
            <CardContent className="pt-6">
              <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
                <Gift className="h-5 w-5 text-primary" />
                Chính sách hoa hồng
              </h3>
              <div className="space-y-2 text-sm">
                <p>• <strong>CTV mới:</strong> 5% trên tổng giá trị đơn hàng</p>
                <p>• <strong>CTV đạt 20 đơn/tháng:</strong> Nâng lên 7%</p>
                <p>• <strong>CTV đạt 50 đơn/tháng:</strong> Nâng lên 10%</p>
                <p>• <strong>Ví dụ:</strong> Đơn hàng 100.000đ → Hoa hồng 5.000đ - 10.000đ</p>
                <p className="text-muted-foreground mt-4">
                  * Hoa hồng được tính sau khi đơn hàng hoàn thành và khách nhận hàng thành công.
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Registration form */}
          <Card>
            <CardHeader>
              <CardTitle>Đăng ký làm CTV</CardTitle>
              <CardDescription>
                Điền thông tin bên dưới để đăng ký trở thành cộng tác viên
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Họ tên *</Label>
                    <Input
                      id="name"
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      placeholder="Nguyễn Văn A"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="phone">Số điện thoại *</Label>
                    <Input
                      id="phone"
                      value={formData.phone}
                      onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                      placeholder="0912345678"
                      required
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    placeholder="email@example.com"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="socialLink">Link Facebook/TikTok/Instagram *</Label>
                  <Input
                    id="socialLink"
                    value={formData.socialLink}
                    onChange={(e) => setFormData({ ...formData, socialLink: e.target.value })}
                    placeholder="https://facebook.com/yourprofile"
                    required
                  />
                  <p className="text-xs text-muted-foreground">
                    Link profile mạng xã hội để admin liên hệ và xác minh
                  </p>
                </div>

                <div className="border-t pt-4">
                  <h4 className="font-medium mb-4">Thông tin nhận hoa hồng (tùy chọn)</h4>
                  <div className="grid md:grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="bankName">Ngân hàng</Label>
                      <Input
                        id="bankName"
                        value={formData.bankName}
                        onChange={(e) => setFormData({ ...formData, bankName: e.target.value })}
                        placeholder="Vietcombank"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="bankAccount">Số tài khoản</Label>
                      <Input
                        id="bankAccount"
                        value={formData.bankAccount}
                        onChange={(e) => setFormData({ ...formData, bankAccount: e.target.value })}
                        placeholder="0123456789"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="accountName">Chủ tài khoản</Label>
                      <Input
                        id="accountName"
                        value={formData.accountName}
                        onChange={(e) => setFormData({ ...formData, accountName: e.target.value })}
                        placeholder="NGUYEN VAN A"
                      />
                    </div>
                  </div>
                </div>

                <Button type="submit" className="w-full" disabled={isSubmitting}>
                  {isSubmitting ? "Đang gửi..." : "Đăng ký làm CTV"}
                </Button>
              </form>
            </CardContent>
          </Card>

          {/* Check status */}
          <div className="mt-8 text-center">
            <p className="text-muted-foreground">
              Đã đăng ký? <a href="/affiliate-dashboard" className="text-primary hover:underline">Kiểm tra trạng thái và hoa hồng</a>
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
